### ISSUE TITLE
show/hide Statusbar issue

### ISSUE THREAD

**Issue by ameer-taghavi** [chrizuuu/react-native-gallery-preview#11]
show/hide statusbar has incorrect behaviour 

https://github.com/user-attachments/assets/a88a2a61-e3fd-49dd-9f75-0282b4444e31

**Comment by krzysztofbonecki** [comment]
I'll take a look at it at the weekend

**Comment by chrizuuu** [comment]
I'll take a look at it at the weekend

**Comment by mehuljetani** [comment]
@ameer-taghavi @chrizuuu 
I have resolved this Here, https://github.com/chrizuuu/react-native-gallery-preview/pull/12

**Comment by chrizuuu** [comment]
Fixed in [1.2.3](https://github.com/chrizuuu/react-native-gallery-preview/releases/tag/v1.2.3)

@mehuljetani , as I mentioned in PR great thanks for your support, your fix was used in the context of StatusBar for android, for ios however I prepared another solution.

**Comment by ameer-taghavi** [comment]
@chrizuuu, @mehuljetani 

I added `statusBarTranslucent` to hide white gap in Modal in `ModalContainer.tsx` but why can't hide statusbar in android?
![Screenshot_1727074036](https://github.com/user-attachments/assets/8e143890-054c-46e3-84a9-653cd7be0474)

zoomed:
![Screenshot_1727074079](https://github.com/user-attachments/assets/27c5dc57-89e2-4b5d-b016-4d80637d3a99)

**Comment by ameer-taghavi** [comment]
> @chrizuuu, @mehuljetani
> 
> I added `statusBarTranslucent` to hide white gap in Modal in `ModalContainer.tsx` but why can't hide statusbar in android? ![Screenshot_1727074036](https://private-user-images.githubusercontent.com/12966060/369773152-8e143890-054c-46e3-84a9-653cd7be0474.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMjg4MTksIm5iZiI6MTcyODEyODUxOSwicGF0aCI6Ii8xMjk2NjA2MC8zNjk3NzMxNTItOGUxNDM4OTAtMDU0Yy00NmUzLTg0YTktNjUzY2Q3YmUwNDc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDExNDE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0N2M1ZTVkZTdkN2ViMTAwMDNhN2I4OGFmZTI1Y2RkN2QwYTQyYjEwMTM1ODIzNTMwMjhmYTM1ZWE2MDkyN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZzTMjPCYQE-UsvgtmiTDmrWSvQUbU_gUXLKzjO3rL1Q)
> 
> zoomed: ![Screenshot_1727074079](https://private-user-images.githubusercontent.com/12966060/369773355-27c5dc57-89e2-4b5d-b016-4d80637d3a99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMjg4MTksIm5iZiI6MTcyODEyODUxOSwicGF0aCI6Ii8xMjk2NjA2MC8zNjk3NzMzNTUtMjdjNWRjNTctODllMi00YjVkLWIwMTYtNGQ4MDYzN2QzYTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDExNDE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkYmEwMDIzMzhjMjFjOTE5ZDFlN2FiZTUyNTc0Y2QxNTc3YTc4NWNmYjkxZjQxMjgxMGYxOGM2ZDc4ODYxNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fVh5GrrfGrzB_eOb5157bec2nzSPpwoXknh4SVkp3Xw)

@chrizuuu @mehuljetani please review it 🙏🏻

**Comment by chrizuuu** [comment]
@ameer-taghavi 
As far as I know, this parameter doesnt hide the StatusBar but only causes the modal to render under the StatusBar.

**Comment by ameer-taghavi** [comment]
@chrizuuu 
Please add statusBarTranslucent to hide white gap in Modal 🙏🏻
