### ISSUE TITLE
找不到GalleryStatusBar

### ISSUE THREAD

**Issue by Seven163** [chrizuuu/react-native-gallery-preview#14]
Error: Unable to resolve module ./components/GalleryStatusBar/GalleryStatusBar

**Comment by chrizuuu** [comment]
It looks like you're facing an issue with module resolution in rn Here are a couple of steps that might help resolve this:

- Clear the Cache, Sometimes, the Metro bundler might have a stale cache
```
yarn start --reset-cache
```
- If clearing the cache doesn't work, try deleting node_modules and reinstalling all packages:

```
rm -rf node_modules
yarn install
```

And please, next time don't use chinese characters in titles/descriptions,

**Comment by Seven163** [comment]
> It looks like you're facing an issue with module resolution in rn Here are a couple of steps that might help resolve this:
> 
> * Clear the Cache, Sometimes, the Metro bundler might have a stale cache
> 
> ```
> yarn start --reset-cache
> ```
> 
> * If clearing the cache doesn't work, try deleting node_modules and reinstalling all packages:
> 
> ```
> rm -rf node_modules
> yarn install
> ```
> 
> And please, next time don't use chinese characters in titles/descriptions,

Still could not [resolved.

**Comment by Seven163** [comment]
![WX20240927-092935@2x](https://github.com/user-attachments/assets/3a372219-fb6a-4fa6-b99f-aa4d3edbab78)

**Comment by Seven163** [comment]
![Uploading WX20240927-093120@2x.png…]()
![Uploading WX20240927-092935@2x.png…]()

**Comment by krzysztofbonecki** [comment]
your screenshots don't work

**Comment by chrizuuu** [comment]
your screenshots don't work

**Comment by Seven163** [comment]
![WX20240927-093120@2x](https://github.com/user-attachments/assets/67a318d6-58e9-4b30-a75e-2c2cb1a70859)
![WX20240927-092935@2x](https://github.com/user-attachments/assets/fdf661f5-7ee7-4106-b383-43f806240067)
@chrizuuu had uploaded

**Comment by Seven163** [comment]
突然想到了，项目工程是在Harmony 里面 所以找不到 GalleryStatusBar  请问是否可以为Harmony 解决呢

**Comment by chrizuuu** [comment]
Version [1.3.1](https://github.com/chrizuuu/react-native-gallery-preview/releases/tag/v1.3.1) where StatusBar now has a defautl component for systems other than IOS. 

And please use English when you write issues, next time I will just automatically close such topic.
