### ISSUE TITLE
When the number of photos exceeds 10, the UI's FPS drops significantly on Android

### ISSUE THREAD

**Issue by chinamcafee** [chrizuuu/react-native-gallery-preview#2]
My Android device use Snapdragon 8 Gen 2 Mobile Platform. 

When the number of photos less than 10, the photo slide smoothly and the FPS is around 100+, but when the number of photos exceeds 10, the UI's FPS drops significantly to about 10~20. 

How can this issue be optimized? Any help would be greatly appreciated.

**Comment by chrizuuu** [comment]
Hi, thanks for reporting the problem. 
I detected that simultaneous rendering was not working properly which could cause performance issues. I have uploaded a release [1.0.6](https://github.com/chrizuuu/react-native-gallery-preview/releases/tag/v1.0.6) containing a fix. Please check and let me know if the problem disappeared

**Comment by chinamcafee** [comment]
Thanks a lot, the new version of the code is working fine!  :)
