### ISSUE TITLE
Change Background Color

### ISSUE THREAD

**Issue by supergianlu** [chrizuuu/react-native-gallery-preview#5]
Hi, thank you for this library!
Could you add the possibility to change the background color of the gallery?
Thanks.

**Comment by chrizuuu** [comment]
Hi, first of all thanks for using my library.

I released version 1.1.1 in which I added two new props: backgroundColor and headerTextColor which allow you to change the background of the gallery and the text in the header.

**Comment by supergianlu** [comment]
Thank you, super fast! 💪🏻
