### ISSUE TITLE
Rotate device

### ISSUE THREAD

**Issue by ameer-taghavi** [chrizuuu/react-native-gallery-preview#8]
when rotate device, these issues happen randomly:
show wrong image or not show image

**Comment by chrizuuu** [comment]
Hi, thanks for reporting the bug. The problem actually occurred when the user was in a photo other than the first one.
Anyway, the fix is already uploaded: https://github.com/chrizuuu/react-native-gallery-preview/releases/tag/v1.1.4

**Comment by ameer-taghavi** [comment]
in android still has bug. when user is in photo other than the first one
![Screenshot_1725967339](https://github.com/user-attachments/assets/5a99b845-ef50-49c8-b9f2-f16c08d2d4d7)
