### ISSUE TITLE
Landscape issue

### ISSUE THREAD

**Issue by ameer-taghavi** [chrizuuu/react-native-gallery-preview#9]
in android still has bug. when user is in photo other than the first one
![Screenshot_1725967339](https://github.com/user-attachments/assets/5a99b845-ef50-49c8-b9f2-f16c08d2d4d7)

_Originally posted by @ameer-taghavi in https://github.com/chrizuuu/react-native-gallery-preview/issues/8#issuecomment-2340397184_

**Comment by chrizuuu** [comment]
[fixed](https://github.com/chrizuuu/react-native-gallery-preview/releases/tag/v1.2.2)
